config/routes.rb
  FramgiaTraining::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :examinations do
    resources :answer_sheets do
      resources :answer_sheet_details, only: [:show] do
      end
    end
  end
  resources :questions do
    resources :answers do
    end
  end
  resources :exam_questions do
    resources :exam_question_details do
    end
  end
  resources :question_groups
  resources :levels
  resources :subjects  do
    resources :subject_question_groups do
    end
  end
  resources :exam_sessions  do
    resources :exam_session_details do
    end
  end
  resources :exports
  resources :imports
  root  'static_pages#home'
  match 'examinations/:examination_id/answer_sheets/:answer_sheet_id/answer_sheet_details/:id/:attachment', to: 'answer_sheet_details#show', as: "download", via: 'get'
  match 'users/:id/:admin', to: 'users#update', as: "admin_user", via: 'patch'
  match '/admin',  to: 'admin#index',            via: 'get'
  match '/monitor',  to: 'monitor#index',            via: 'get'
  match '/generate',  to: 'monitor#generate',            via: 'get'
  match '/update_sequence',  to: 'monitor#update_sequence',            via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/home',    to: 'static_pages#home',    via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',    to: 'static_pages#about',    via: 'get'
  match '/contactus',    to: 'static_pages#contact',    via: 'get'

  

end

app/models/question_group.rb
class QuestionGroup < ActiveRecord::Base
  self.table_name = 'training_question_group'
  self.primary_key = 'question_group_id'
  default_scope -> { order('training_question_group.question_group_id') }

  before_create :default_active_values

  def default_active_values
    self.active_flag ||= 1
  end
end

app/controllers/question_groups_controller.rb
class QuestionGroupsController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_action :admin_user

  def index
    @question_groups = QuestionGroup.paginate(page: params[:page], per_page: 10, :conditions => { :active_flag => 1})
  end

  def show
    @question_group = QuestionGroup.find(params[:id])
  end

  def new
    @question_group = QuestionGroup.new
  end

  def create
    #binding.pry
    @question_group = QuestionGroup.new(question_group_params)
    if @question_group.save
      flash[:success] = "Level created"
      redirect_to question_groups_path
    else
      render 'new'
    end
  end

  def edit
    @question_group = QuestionGroup.find(params[:id])
  end

  def update
    @question_group = QuestionGroup.find(params[:id])
    if @question_group.update_attributes(question_group_params)
      flash[:success] = "Question Group updated"
      redirect_to question_groups_path
    else
      render 'edit'
    end
  end

  def destroy
    QuestionGroup.find(params[:id]).update_attributes(active_flag: 0)
    flash[:success] = "Question Group destroyed."
    redirect_to question_groups_path
  end

  private

  def question_group_params
    params.require(:question_group).permit(:question_group_name)
  end

  # Before filters

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def admin_user
    redirect_to(root_url) unless current_user.user_admin?
  end
end

app/views/question_groups/edit.html.erb
<% provide(:title, 'Question Group') %>
<h1>Question Group</h1>

<div class="row">
  <div class="span7 offset2">
    <%= form_for(@question_group) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.label :question_group_name %>
        <%= f.text_field :question_group_name %>

        <%= f.submit "Update Question Group", class: "btn btn-large btn-primary", style: "margin-top: 20px;" %>
    <% end %>
  </div>
</div>

app/views/question_groups/index.html.erb
<% provide(:title, 'All question groups') %>
<h1>All question groups</h1>

<%= will_paginate @question_groups %>

<ul class="users">
  <% @question_groups.each do |question_group| %>
  <li>
    <span style="width: 5%; display: inline-block; float: left;"><%= link_to "#" + question_group.question_group_id.to_s, question_group_path(question_group) %></span>
    <span style="width: 50%; display: inline-block; float: left;">&nbsp;<%= question_group.question_group_name %></span>
    <span style="width: 10%; display: inline-block; float: left;"><%= link_to "Edit", edit_question_group_path(question_group) %>&nbsp;&nbsp;<%= link_to "Delete", question_group_path(question_group), method: "delete" %></span>
  </li>
  <% end %>
</ul>

<%= will_paginate @question_groups %>

<div style="width: 100%">
  <%= link_to "Create new", new_question_group_path, class: "btn btn-large btn-primary", style: "margin-top: 10px;" %>
</div>

app/views/question_groups/new.html.erb
<% provide(:title, 'Question Group') %>
<h1>Question Group</h1>

<div class="row">
  <div class="span7 offset2">
  <%= form_for(@question_group) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :question_group_name %>
      <%= f.text_field :question_group_name %>

      <%= f.submit "Create Question Group", class: "btn btn-large btn-primary", style: "margin-top: 20px;" %>
  <% end %>
</div>
</div>

app/views/question_groups/show.html.erb
<% provide(:title, 'Question Group') %>
<h1>Question Group</h1>

<div class="row">
  Name: <%= @question_group.question_group_name %>
</div>