config/routes.rb
  FramgiaTraining::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :examinations do
    resources :answer_sheets do
      resources :answer_sheet_details, only: [:show] do
      end
    end
  end
  resources :questions do
    resources :answers do
    end
  end
  resources :exam_questions do
    resources :exam_question_details do
    end
  end
  resources :question_groups
  resources :levels
  resources :subjects  do
    resources :subject_question_groups do
    end
  end
  resources :exam_sessions  do
    resources :exam_session_details do
    end
  end
  resources :exports
  resources :imports
  root  'static_pages#home'
  match 'examinations/:examination_id/answer_sheets/:answer_sheet_id/answer_sheet_details/:id/:attachment', to: 'answer_sheet_details#show', as: "download", via: 'get'
  match 'users/:id/:admin', to: 'users#update', as: "admin_user", via: 'patch'
  match '/admin',  to: 'admin#index',            via: 'get'
  match '/monitor',  to: 'monitor#index',            via: 'get'
  match '/generate',  to: 'monitor#generate',            via: 'get'
  match '/update_sequence',  to: 'monitor#update_sequence',            via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/home',    to: 'static_pages#home',    via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',    to: 'static_pages#about',    via: 'get'
  match '/contactus',    to: 'static_pages#contact',    via: 'get'

  

end

app/views/admin/_examination.html.erb
<li>
  <span style="display: inline-block; width: 20%; font-weight: bold;"><%= I18n.l(examination.created_at) %></span>
  <span style="display: inline-block; width: 30%;"><%= examination.user.full_name %></span>
  <span style="display: inline-block; width: 10%;"><%= examination_status examination.status %></span>
  <span style="display: inline-block; width: 20%;">
  <% if examination.conclusion %>
  <%= examination.conclusion.conclusion_name %>
  <% end %>
  </span>
  <span style="display: inline-block; width: 10%;">
  <% if examination.status == 1 %>
      <%= link_to "Check", examination_path(examination) + "?examination[status]=2", :method => :put %>
  <% end %>
  </span>
  <ul>
    <% examination.answer_sheets.each do |answer_sheet| %>
        <li>
          <span style="display: inline-block; width: 30%;"><%= answer_sheet.subject.subject_name %></span>
      <span style="display: inline-block; width: 10%;"><% if examination.status != 1 %>
      <%= answer_sheet.exam_result %>/<%= answer_sheet.exam_question.number_question %>
      <% end %>&nbsp;</span>
          <span style="display: inline-block; width: 20%;"><%= exam_time_s(answer_sheet.exam_time) %>&nbsp;</span>
      <span style="display: inline-block; width: 10%;">
      <% if answer_sheet.started_at.nil? %>
      <%= link_to "Start", edit_examination_answer_sheet_path(examination, answer_sheet) %>
      <% else %>
      <%= link_to "View", examination_answer_sheet_path(examination, answer_sheet) %>
      <% end %>
      </span>
          <span style="display: inline-block; width: 25%;">&nbsp;</span>
        </li>
    <% end %>
  </ul>
</li>

app/views/admin/index.html.erb
<% provide(:title, 'All examinations') %>
<h1>All examinations</h1>

<%= will_paginate @examinations %>
<ul class="users">
  <%= render partial: "admin/examination", :collection => @examinations %>
</ul>
<%= will_paginate @examinations %>