config/routes.rb
  FramgiaTraining::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :examinations do
    resources :answer_sheets do
      resources :answer_sheet_details, only: [:show] do
      end
    end
  end
  resources :questions do
    resources :answers do
    end
  end
  resources :exam_questions do
    resources :exam_question_details do
    end
  end
  resources :question_groups
  resources :levels
  resources :subjects  do
    resources :subject_question_groups do
    end
  end
  resources :exam_sessions  do
    resources :exam_session_details do
    end
  end
  resources :exports
  resources :imports
  root  'static_pages#home'
  match 'examinations/:examination_id/answer_sheets/:answer_sheet_id/answer_sheet_details/:id/:attachment', to: 'answer_sheet_details#show', as: "download", via: 'get'
  match 'users/:id/:admin', to: 'users#update', as: "admin_user", via: 'patch'
  match '/admin',  to: 'admin#index',            via: 'get'
  match '/monitor',  to: 'monitor#index',            via: 'get'
  match '/generate',  to: 'monitor#generate',            via: 'get'
  match '/update_sequence',  to: 'monitor#update_sequence',            via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/home',    to: 'static_pages#home',    via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',    to: 'static_pages#about',    via: 'get'
  match '/contactus',    to: 'static_pages#contact',    via: 'get'

  

end

app/models/exam_session.rb
class ExamSession < ActiveRecord::Base
  self.table_name = 'training_exam_session'
  self.primary_key = 'exam_session_id'
  default_scope -> { order('exam_date DESC') }

  attr_accessor :subject_ids

  before_save :default_active_values
  after_save :make_exam_session_details

  has_many :exam_session_details, foreign_key: "exam_session_id", class_name:  "ExamSessionDetail", dependent: :destroy, :conditions => "training_exam_session_detail.active_flag = 1"
  belongs_to :level, class_name: "Level"
  accepts_nested_attributes_for :exam_session_details

  def number_question
    total = 0
    self.exam_question_details.each do |exam_question_detail|
      total = total + exam_question_detail.number_question
    end
    total
  end

  def all_exam_question_detail
    question_groups = self.subject.question_groups
    all_exam_question_details = []
    question_group_ids = []
    if !exam_question_details.nil?
      exam_question_details.each do |exam_question_detail|
        exam_question_detail.used = 1
        all_exam_question_details << exam_question_detail
        question_group_ids << exam_question_detail.question_group_id
      end
    end
    if !question_groups.nil?
      question_groups.each do |question_group|
        if question_group_ids.index(question_group.question_group_id).nil?
          exam_question_detail = ExamQuestionDetail.new(exam_question_id: self.exam_question_id, question_group_id: question_group.question_group_id,subject_id: self.subject_id, used: 0)
          all_exam_question_details << exam_question_detail
        end
      end
    end
    all_exam_question_details
  end

  def exam_question_detail?(question_group_id)
    if exam_question_details.nil?
      false
    else
      exist = false
      exam_question_details.each do |exam_question_detail|
        if exam_question_detail.question_group_id == question_group_id
          exist = true
        end
      end
      exist
    end
  end

  def default_active_values
    self.active_flag ||= 1
  end

  def make_exam_session_details
    exam_session_detail_map = {}
    _exam_session_details = []
    if !self.exam_session_id.nil?
      _exam_session_details = ExamSessionDetail.where(exam_session_id: self.exam_session_id, active_flag: 1)
    end
    if !_exam_session_details.nil? && !_exam_session_details.empty?
      _exam_session_details.each do |exam_session_detail|
        exam_session_detail_map[exam_session_detail.subject_id] = exam_session_detail
      end
    end
    if !self.subject_ids.nil? && !self.subject_ids.empty?
      index = 1
      self.subject_ids.each do |subject_id|
        if subject_id.nil? || subject_id.empty?
          next
        end
        if exam_session_detail_map.has_key?(subject_id.to_i)
          exam_session_detail = exam_session_detail_map[subject_id.to_i]
          exam_session_detail.no = index
          exam_session_detail.save
          exam_session_detail_map.delete(subject_id.to_i)
        else
          ExamSessionDetail.create!(exam_session_id: self.exam_session_id, subject_id: subject_id.to_i, no: index)
        end
        index = index + 1
      end
    end
    if !exam_session_detail_map.nil? && !exam_session_detail_map.empty?
      exam_session_detail_map.each do |subject_id, exam_session_detail|
        exam_session_detail.active_flag = 0
        exam_session_detail.save
      end
    end
  end

end

app/controllers/exam_sessions_controller.rb
class ExamSessionsController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_action :admin_user

  def index
    @user = current_user
    @exam_sessions = ExamSession.paginate(page: params[:page], per_page: 10, :conditions => { :active_flag => 1})
  end

  def show
    @exam_session = ExamSession.find(params[:id])
  end

  def new
    @exam_session = ExamSession.new
    @levels = Level.where(active_flag: 1)
    @subjects = []
    @remain_subjects = Subject.where(active_flag: 1)
  end

  def create
    @user = current_user
    @exam_session = ExamSession.new(exam_session_params)
    if @exam_session.save
      flash[:success] = "Exam Session created"
      redirect_to exam_sessions_path
    else
      render 'new'
    end
  end

  def edit
    @exam_session = ExamSession.find(params[:id])
    @levels = Level.where(active_flag: 1)
    @subjects = []
    subject_ids = []
    if !@exam_session.exam_session_details.nil?
      @exam_session.exam_session_details.each do |exam_session_detail|
        subject_ids << exam_session_detail.subject_id
        @subjects << exam_session_detail.subject
      end
    end
    if !subject_ids.nil? && !subject_ids.empty?
      @remain_subjects = Subject.where("subject_id NOT IN (:subject_ids) AND active_flag = :active_flag", :subject_ids => subject_ids, :active_flag => 1)
    else
      @remain_subjects = Subject.where(active_flag: 1)
    end
  end

  def update
    @exam_session = ExamSession.find(params[:id])
    if @exam_session.update_attributes(exam_session_params)
      flash[:success] = "Exam Session updated"
      redirect_to exam_sessions_path
    else
      render 'edit'
    end
  end

  def destroy
    ExamSession.find(params[:id]).update_attributes(:active_flag => 0)
    flash[:success] = "Exam Session destroyed."
    redirect_to exam_sessions_path
  end

  private
  def exam_session_params
    params.require(:exam_session).permit(:level_id, :exam_session_name, :exam_date, :exam_duration, :subject_ids => [])
  end

  # Before filters

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def admin_user
    redirect_to(root_url) unless current_user.user_admin?
  end

end

app/views/exam_sessions/edit.html.erb
<% provide(:title, 'Exam Session') %>
<h1>Exam Session</h1>

<div class="row">
  <div class="span7 offset2">
    <%= form_for(@exam_session, html: {onsubmit: "selectAllOfSelect($('#exam_session_subject_ids'))"}) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.label :level_id %>
        <%= f.select :level_id, options_from_collection_for_select(@levels, "level_id", "level_name"), style: "display: inline-block; width: 200px;" %>

        <%= f.label :exam_session_name %>
        <%= f.text_field :exam_session_name %>

        <%= f.label :exam_date %>
        <%= f.text_field :exam_date %>

        <%= f.label :exam_duration %>
        <%= f.text_field :exam_duration %>

        <%= f.label :subject_ids %>
        <div>
          <%= select_tag "remain_subject_ids", options_from_collection_for_select(@remain_subjects, "subject_id", "subject_name"), :multiple => true , style: "display: inline-block; width: 200px; float: left;" %>
          <a href="javascript: void(0)" onclick="move2Select($('#remain_subject_ids'), $('#exam_session_subject_ids'));" style="position: relative; top:15px; left: 65px;">&gt;&gt;</a>
          <a href="javascript: void(0)" onclick="move2Select($('#exam_session_subject_ids'), $('#remain_subject_ids'));" style="position: relative; top:40px; left: 45px;">&lt;&lt;</a>
          <%= f.select :subject_ids, options_from_collection_for_select(@subjects, "subject_id", "subject_name"), {}, :multiple => true , style: "display: inline-block; width: 200px;; float: right;" %>
        </div>

        <%= f.submit "Update Exam Question", class: "btn btn-large btn-primary", style: "margin-top: 20px;" %>
    <% end %>
  </div>
</div>

app/views/exam_sessions/index.html.erb
<% provide(:title, 'All exam sessions') %>
<h1>All exam sessions</h1>

<%= will_paginate @exam_sessions %>

<ul class="users">
  <% @exam_sessions.each do |exam_session| %>
  <li>
    <span style="width: 5%; display: inline-block; float: left;"><%= link_to "#" + exam_session.exam_session_id.to_s, exam_session_path(exam_session) %></span>
    <span style="width: 25%; display: inline-block; float: left;">&nbsp;<%= exam_session.exam_session_name %></span>
    <span style="width: 20%; display: inline-block; float: left;"><%= exam_session.level.level_name %></span>
    <span style="width: 20%; display: inline-block; float: left;"><%= exam_session.exam_date %></span>
    <span style="width: 20%; display: inline-block; float: left;"><%= exam_session.exam_duration %></span>
    <span style="width: 10%; display: inline-block; float: left;"><%= link_to "Edit", edit_exam_session_path(exam_session) %>&nbsp;&nbsp;<%= link_to "Delete", exam_session_path(exam_session), method: "delete" %></span>
  </li>
  <% end %>
</ul>

<%= will_paginate @exam_sessions %>

<%= link_to "Create new", new_exam_session_path, class: "btn btn-large btn-primary", style: "margin-top: 10px;" %>

app/views/exam_sessions/new.html.erb
<% provide(:title, 'Exam Session') %>
<h1>Exam Session</h1>

<div class="row">
  <div class="span7 offset2">
  <%= form_for(@exam_session, html: {onsubmit: "selectAllOfSelect($('#exam_session_subject_ids'))"}) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :level_id %>
      <%= f.select :level_id, options_from_collection_for_select(@levels, "level_id", "level_name"), style: "display: inline-block; width: 200px;" %>

      <%= f.label :exam_session_name %>
      <%= f.text_field :exam_session_name %>

      <%= f.label :exam_date %>
      <%= f.text_field :exam_date %>

      <%= f.label :exam_duration %>
      <%= f.text_field :exam_duration %>

      <%= f.label :subject_ids %>
      <div>
      <%= select_tag "remain_subject_ids", options_from_collection_for_select(@remain_subjects, "subject_id", "subject_name"), :multiple => true , style: "display: inline-block; width: 200px; float: left;" %>
      <a href="javascript: void(0)" onclick="move2Select($('#remain_subject_ids'), $('#exam_session_subject_ids'));" style="position: relative; top:15px; left: 65px;">&gt;&gt;</a>
      <a href="javascript: void(0)" onclick="move2Select($('#exam_session_subject_ids'), $('#remain_subject_ids'));" style="position: relative; top:40px; left: 45px;">&lt;&lt;</a>
      <%= f.select :subject_ids, options_from_collection_for_select(@subjects, "subject_id", "subject_name"), {}, :multiple => true , style: "display: inline-block; width: 200px;; float: right;" %>
      </div>

      <%= f.submit "Create Exam Question", class: "btn btn-large btn-primary", style: "margin-top: 20px;" %>
  <% end %>
</div>
</div>

app/views/exam_sessions/show.html.erb
<% provide(:title, 'Exam Session') %>
<h1>Exam Session</h1>

<div class="row">
  <div class="span7 offset2">
  Name: <%= @exam_session.exam_session_name %>
  <br>
  Level: <%= @exam_session.level.level_name %>
  <br>
  Exam date: <%= @exam_session.exam_date %>
  <br>
  Exam duration: <%= @exam_session.exam_duration %>

  <div style="margin-top: 20px;">Details</div>
  <div id="__option_answer">
    <ul>
      <li>
        <span style="display: inline-block; width: 50px;">No</span>
        <span style="display: inline-block; width: 250px;">Question group</span>
      </li>
      <% @exam_session.exam_session_details.each do |exam_session_detail| %>
      <li>
        <span style="display: inline-block; width: 50px;"><%= exam_session_detail.no %>.</span>
        <span style="display: inline-block; width: 250px;"><%= exam_session_detail.subject.subject_name %></span>
      </li>
      <% end %>
    </ul>
  </div>
    </div>
</div>